test3

diff --git a/.github/workflows/pre-merge-check.yml b/.github/workflows/pre-merge-check.yml
--- a/.github/workflows/pre-merge-check.yml
+++ b/.github/workflows/pre-merge-check.yml
@@ -1,34 +1,37 @@
-# .github/workflows/pre-merge-check.yml
 name: Pre-Merge Checks
 
 on:
   pull_request:
     branches:
-      - main  # Adjust to the target branch for the checks
+      - main
 
 jobs:
-  verify-branch-protection:
+  validate-commits:
     runs-on: ubuntu-latest
 
     steps:
       - name: Check out the repository
         uses: actions/checkout@v3
 
-      - name: Verify Branch Protection
+      # Step to check if branch protection is enabled for master
+      - name: Check branch protection for main
         run: |
-          echo "Test ... Checking branch protection settings for master..."
+          echo "Checking branch protection settings for main..."
 
-          # Use GitHub's REST API to get branch protection details
+          # Use GitHub API to get branch protection details
           response=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
             -H "Accept: application/vnd.github.v3+json" \
             "https://api.github.com/repos/${{ github.repository }}/branches/main/protection")
 
-          # Check if branch protection is enabled
+          # Check if branch protection is enabled by looking for 'required_status_checks'
           if echo "$response" | grep -q '"required_status_checks"'; then
-            echo "Branch protection is correctly configured on master."
+            echo "Branch protection is enabled on master."
           else
             echo "Error: Branch protection is not enabled on master."
-            exit 1
+            exit 1  # Fail the workflow if branch protection is not enabled
           fi
 
-          # Additional checks as needed
+      # check validate commit script
+      - name: Run validate commits script
+        run: |
+          chmod +x ./validate-commits.sh && ./validate-commits.sh
